/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-04 09:56:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.chart;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import semi.kh.chart.model.vo.Favorite;
import semi.kh.member.model.vo.*;

public final class showChart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1546586259887L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1546256583663L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("semi.kh.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("semi.kh.chart.model.vo.Favorite");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

/* 	String typeFlag = (String)request.getAttribute("typeFlag");
	List<Favorite> favoriteChart = null;	
	int totalCount = 1;
	double desktop = 1;
	double notebook = 1;
	double smartPhone = 1;
	double tablet = 1;
	double wearable = 1;
	double monitor = 1;
	if("gender".equals(typeFlag)){
	favoriteChart = (List<Favorite>)request.getAttribute("gender");
	 totalCount = favoriteChart.get(0).getDesktop()+favoriteChart.get(0).getMonitor()+favoriteChart.get(0).getNotebook()+favoriteChart.get(0).getSmartPhone()+favoriteChart.get(0).getTablet()+favoriteChart.get(0).getWearable();
	desktop = Math.round((double)favoriteChart.get(0).getDesktop()/totalCount*1000.0)/10.0;
	notebook = Math.round(((double)favoriteChart.get(0).getNotebook()/totalCount)*1000.0)/10.0;
	smartPhone = Math.round(((double)favoriteChart.get(0).getSmartPhone()/totalCount)*1000.0)/10.0;
	tablet = Math.round(((double)favoriteChart.get(0).getTablet()/totalCount)*1000.0)/10.0;
	wearable = Math.round(((double)favoriteChart.get(0).getWearable()/totalCount)*1000.0)/10.0;
	monitor = Math.round(((double)favoriteChart.get(0).getMonitor()/totalCount)*1000.0)/10.0; 
	} */


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>SHOPINGMALL</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/Chart.bundle.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- 로그인 폼 -->\r\n");
      out.write("\t\t\t<div class=\"login-container\">\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/member/login\"\r\n");
      out.write("\t\t\t\t\t  method=\"post\" \r\n");
      out.write("\t\t\t\t\t  id=\"loginFrm\">\r\n");
      out.write("\t\t\t\t\t  <table>\r\n");
      out.write("\t\t\t\t\t  \t<tr>\r\n");
      out.write("\t\t\t\t\t  \t\t<td>\r\n");
      out.write("\t\t\t\t\t  \t\t\t<input type=\"text\" \r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   name=\"memberId\"\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   id=\"memberId\"\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   value=\"\"\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   placeholder=\"아이디\"/>\r\n");
      out.write("\t\t\t\t\t  \t\t</td>\r\n");
      out.write("\t\t\t\t\t  \t\t<td></td>\r\n");
      out.write("\t\t\t\t\t  \t</tr>\r\n");
      out.write("\t\t\t\t\t  \t<tr>\r\n");
      out.write("\t\t\t\t\t  \t\t<td>\r\n");
      out.write("\t\t\t\t\t  \t\t\t<input type=\"password\" \r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   name=\"password\" \r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   id=\"password\" \r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   placeholder=\"비밀번호\" />\r\n");
      out.write("\t\t\t\t\t  \t\t</td>\r\n");
      out.write("\t\t\t\t\t  \t\t<td>\r\n");
      out.write("\t\t\t\t\t  \t\t\t<input type=\"submit\" \r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   value=\"로그인\" \r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   onclick=\"\"/>\r\n");
      out.write("\t\t\t\t\t  \t\t</td>\r\n");
      out.write("\t\t\t\t\t  \t</tr>\r\n");
      out.write("\t\t\t\t\t  \t<tr>\r\n");
      out.write("\t\t\t\t\t  \t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t<input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   name=\"saveId\"\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   id=\"saveId\" />\r\n");
      out.write("\t\t\t\t\t  \t\t\t<label for=\"saveId\">\r\n");
      out.write("\t\t\t\t\t  \t\t\t아이디저장\r\n");
      out.write("\t\t\t\t\t  \t\t\t</label>\r\n");
      out.write("\t\t\t\t\t  \t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t  \t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   value=\"회원가입\"\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/member/memberEnroll'\" />\t   \r\n");
      out.write("\t\t\t\t\t  \t\t</td>\r\n");
      out.write("\t\t\t\t\t  \t</tr>\r\n");
      out.write("\t\t\t\t\t  </table>\r\n");
      out.write("\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 로그인 폼 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 메인메뉴 시작 -->\r\n");
      out.write("\t\t\t <nav>\r\n");
      out.write("            <ul class=\"main-nav\">\r\n");
      out.write("               <li><a href=\"#\">Home</a></li>\r\n");
      out.write("               \r\n");
      out.write("               <li><a href=\"#\">모바일</a>               \r\n");
      out.write("                  <ul class=\"sub-nav\">\r\n");
      out.write("                     <li><a href=\"#\">스마트폰</a></li>\r\n");
      out.write("                     <li><a href=\"#\">태블릿</a></li>\r\n");
      out.write("                     <li><a href=\"#\">웨어러블</a></li>\r\n");
      out.write("                  </ul>      \r\n");
      out.write("               </li>\r\n");
      out.write("               \r\n");
      out.write("               <li><a href=\"#\">PC</a>\r\n");
      out.write("                  <ul class=\"sub-nav\">\r\n");
      out.write("                     <li><a href=\"#\">노트북</a></li>\r\n");
      out.write("                     <li><a href=\"#\">모니터</a></li>\r\n");
      out.write("                     <li><a href=\"#\">데스크탑</a></li>\r\n");
      out.write("                  </ul>   \r\n");
      out.write("               </li>\r\n");
      out.write("               \r\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/board/boardList\">고객센터</a></li>\r\n");
      out.write("                              \r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">관리자</a>\r\n");
      out.write("                  <ul class=\"sub-nav\">\r\n");
      out.write("                     <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">회원관리</a></li>                              \r\n");
      out.write("                     <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberManagement\">통계</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </nav>\r\n");
      out.write("         <!-- 메인메뉴 끝 -->\r\n");
      out.write("      </header>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 메인메뉴 끝 -->\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<section id=\"content\">");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath() );
      out.write("/css/chart.css\" />\r\n");
      out.write(" <nav id=\"left-category\"> <!-- 왼쪽 카테고리 -->\r\n");
      out.write("            <input type=\"radio\" name=\"chart\" value=\"1\" onclick=\"div_OnOff();\">선호도 통계 \r\n");
      out.write("            <input type=\"radio\" name=\"chart\" value=\"2\" onclick=\"div_OnOff();\">총판매 통계 \r\n");
      out.write("         <hr />\r\n");
      out.write("\r\n");
      out.write("\t<p>하위카테고리</p>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"con\" style=\"display: none\">\r\n");
      out.write("\t\t<input type=\"radio\" name=\"favorite\" value=\"age\">나이<br /> \r\n");
      out.write("\t\t<input type=\"radio\" name=\"favorite\" value=\"gender\">성별\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"con2\" style=\"display: none\">\r\n");
      out.write("\t\t<input type=\"radio\" name=\"sale\" value=\"region\">지역<br /> \r\n");
      out.write("\t\t<input type=\"radio\" name=\"sale\" value=\"rank\">등급\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div id=\"chartOfGenderM\" class=\"chartOfGender\">\r\n");
      out.write("\t<canvas id=\"maleChart\"></canvas>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"chartOfGenderF\" class=\"chartOfGender\">\r\n");
      out.write("<canvas id=\"femaleChart\"></canvas>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function div_OnOff(){\r\n");
      out.write("\t   // 라디오 버튼 value 값 조건 비교\r\n");
      out.write("\t     \r\n");
      out.write("\t   if($(\"input[name=chart]:checked\").val() == \"1\") {\r\n");
      out.write("\t      $(\"#con\").css(\"display\",\"\"); // 보여줌\r\n");
      out.write("\t      $(\"#con2\").css(\"display\",\"none\");\r\n");
      out.write("\t   }\r\n");
      out.write("\t   else if($(\"input[name=chart]:checked\").val() == \"2\"){\r\n");
      out.write("\t      $(\"#con\").css(\"display\",\"none\"); // 보여줌\r\n");
      out.write("\t      $(\"#con2\").css(\"display\",\"\");\r\n");
      out.write("\t   }\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("$(\"input[name=favorite]\").on(\"click\",function(){\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/admin/chart\",\r\n");
      out.write("\t\tdata : \"searchType=\"+ $(this).val(),\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t$('canvas').css(\"display\",\"false\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i in data){\r\n");
      out.write("\t\t\t\tif(i == 0){\r\n");
      out.write("\t\t\t\t$(\"#femaleChart\").css(\"display\",\"inline\");\r\n");
      out.write("\t\t\t var favoriteChart = data[i];\r\n");
      out.write("\t\t\tvar ctx = $(\"#femaleChart\");\r\n");
      out.write("\t\t\tvar femaleChart = new Chart(ctx, {\r\n");
      out.write("\t\t\t    type: 'doughnut',\r\n");
      out.write("\t\t\t    data: {\r\n");
      out.write("\t\t\t        datasets: [{\r\n");
      out.write("\t\t\t            data: [favoriteChart.smartPhone, favoriteChart.monitor, favoriteChart.notebook, favoriteChart.desktop, favoriteChart.tablet, favoriteChart.wearable],\r\n");
      out.write("\t\t\t            backgroundColor: [\r\n");
      out.write("\t\t\t                'rgba(255, 99, 132, 0.2)',\r\n");
      out.write("\t\t\t                'rgba(54, 162, 235, 0.2)',\r\n");
      out.write("\t\t\t                'rgba(255, 206, 86, 0.2)',\r\n");
      out.write("\t\t\t                'rgba(75, 192, 192, 0.2)',\r\n");
      out.write("\t\t\t                'rgba(153, 102, 255, 0.2)',\r\n");
      out.write("\t\t\t                'rgba(255, 159, 64, 0.2)'\r\n");
      out.write("\t\t\t            ],\r\n");
      out.write("\t\t\t            borderColor: [\r\n");
      out.write("\t\t\t                'rgba(255,99,132,1)',\r\n");
      out.write("\t\t\t                'rgba(54, 162, 235, 1)',\r\n");
      out.write("\t\t\t                'rgba(255, 206, 86, 1)',\r\n");
      out.write("\t\t\t                'rgba(75, 192, 192, 1)',\r\n");
      out.write("\t\t\t                'rgba(153, 102, 255, 1)',\r\n");
      out.write("\t\t\t                'rgba(255, 159, 64, 1)'\r\n");
      out.write("\t\t\t            ],\r\n");
      out.write("\t\t\t            borderWidth: 2\r\n");
      out.write("\t\t\t        }],\r\n");
      out.write("\t\t\t        labels: [\"스마트폰\", \"모니터\", \"노트북\", \"데스크탑\", \"태블릿\", \"웨어러블\"]\r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\t    options: {\r\n");
      out.write("\t\t\t    \t/* rotation: -Math.PI,\r\n");
      out.write("\t\t\t    \t  cutoutPercentage: 30,\r\n");
      out.write("\t\t\t    \t  circumference: Math.PI, */\r\n");
      out.write("\t\t\t    \ttitle :{\r\n");
      out.write("\t\t\t    \t\tdisplay: true,\r\n");
      out.write("\t\t\t    \t\ttext: '여자 선호도',\r\n");
      out.write("\t\t\t    \t\t\r\n");
      out.write("\t\t\t    \t},\r\n");
      out.write("\t\t\t    \tlegend : {\r\n");
      out.write("\t\t\t    \t\tdisplay : true,\r\n");
      out.write("\t\t\t    \t\tposition:'bottom'\t\r\n");
      out.write("\t\t\t    \t\t\r\n");
      out.write("\t\t\t    \t}\r\n");
      out.write("\t\t\t    \t \r\n");
      out.write("\t\t\t    \t/* elements: {\r\n");
      out.write("\t\t\t    \t      center: {\r\n");
      out.write("\t\t\t    \t      text: 'GenderFavorite',\r\n");
      out.write("\t\t\t    \t      color: '#36A2EB', //Default black\r\n");
      out.write("\t\t\t    \t      sidePadding: 15 //Default 20 (as a percentage)\r\n");
      out.write("\t\t\t    \t    }\r\n");
      out.write("\t\t\t    \t  } */\r\n");
      out.write("\t\t\t        /* scales: {\r\n");
      out.write("\t\t\t            yAxes: [{\r\n");
      out.write("\t\t\t                ticks: {\r\n");
      out.write("\t\t\t                    beginAtZero:true\r\n");
      out.write("\t\t\t                }\r\n");
      out.write("\t\t\t            }]\r\n");
      out.write("\t\t\t        } */\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}else if(i == 1){\r\n");
      out.write("\t\t\t$(\"#maleChart\").css(\"display\",\"inline\");\r\n");
      out.write("\t\t\t var favoriteChart = data[i];\r\n");
      out.write("\t\t\tvar ctx = $(\"#maleChart\");\r\n");
      out.write("\t\t\tvar maleChart = new Chart(ctx, {\r\n");
      out.write("\t\t\t    type: 'doughnut',\r\n");
      out.write("\t\t\t    data: {\r\n");
      out.write("\t\t\t        datasets: [{\r\n");
      out.write("\t\t\t            data: [favoriteChart.smartPhone, favoriteChart.monitor, favoriteChart.notebook, favoriteChart.desktop, favoriteChart.tablet, favoriteChart.wearable],\r\n");
      out.write("\t\t\t            backgroundColor: [\r\n");
      out.write("\t\t\t                'rgba(255, 99, 132, 0.2)',\r\n");
      out.write("\t\t\t                'rgba(54, 162, 235, 0.2)',\r\n");
      out.write("\t\t\t                'rgba(255, 206, 86, 0.2)',\r\n");
      out.write("\t\t\t                'rgba(75, 192, 192, 0.2)',\r\n");
      out.write("\t\t\t                'rgba(153, 102, 255, 0.2)',\r\n");
      out.write("\t\t\t                'rgba(255, 159, 64, 0.2)'\r\n");
      out.write("\t\t\t            ],\r\n");
      out.write("\t\t\t            borderColor: [\r\n");
      out.write("\t\t\t                'rgba(255,99,132,1)',\r\n");
      out.write("\t\t\t                'rgba(54, 162, 235, 1)',\r\n");
      out.write("\t\t\t                'rgba(255, 206, 86, 1)',\r\n");
      out.write("\t\t\t                'rgba(75, 192, 192, 1)',\r\n");
      out.write("\t\t\t                'rgba(153, 102, 255, 1)',\r\n");
      out.write("\t\t\t                'rgba(255, 159, 64, 1)'\r\n");
      out.write("\t\t\t            ],\r\n");
      out.write("\t\t\t            borderWidth: 2\r\n");
      out.write("\t\t\t        }],\r\n");
      out.write("\t\t\t        labels: [\"스마트폰\", \"모니터\", \"노트북\", \"데스크탑\", \"태블릿\", \"웨어러블\"]\r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\t    options: {\r\n");
      out.write("\t\t\t    \t/* rotation: -Math.PI,\r\n");
      out.write("\t\t\t    \t  cutoutPercentage: 30,\r\n");
      out.write("\t\t\t    \t  circumference: Math.PI, */\r\n");
      out.write("\t\t\t    \ttitle :{\r\n");
      out.write("\t\t\t    \t\tdisplay: true,\r\n");
      out.write("\t\t\t    \t\ttext: '남자 선호도',\r\n");
      out.write("\t\t\t    \t\t\r\n");
      out.write("\t\t\t    \t},\r\n");
      out.write("\t\t\t    \tlegend : {\r\n");
      out.write("\t\t\t    \t\tdisplay : true,\r\n");
      out.write("\t\t\t    \t\tposition:'bottom'\t\r\n");
      out.write("\t\t\t    \t\t\r\n");
      out.write("\t\t\t    \t}\r\n");
      out.write("\t\t\t    \t \r\n");
      out.write("\t\t\t    \t/* elements: {\r\n");
      out.write("\t\t\t    \t      center: {\r\n");
      out.write("\t\t\t    \t      text: 'GenderFavorite',\r\n");
      out.write("\t\t\t    \t      color: '#36A2EB', //Default black\r\n");
      out.write("\t\t\t    \t      sidePadding: 15 //Default 20 (as a percentage)\r\n");
      out.write("\t\t\t    \t    }\r\n");
      out.write("\t\t\t    \t  } */\r\n");
      out.write("\t\t\t        /* scales: {\r\n");
      out.write("\t\t\t            yAxes: [{\r\n");
      out.write("\t\t\t                ticks: {\r\n");
      out.write("\t\t\t                    beginAtZero:true\r\n");
      out.write("\t\t\t                }\r\n");
      out.write("\t\t\t            }]\r\n");
      out.write("\t\t\t        } */\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("        \t<div>        \t \r\n");
      out.write("        \t\t  주식회사 SEMI_HDJ &nbsp;|&nbsp; CEO HDJ &nbsp;|&nbsp; BUSINESS REGISTRATION 103-88-00990 \r\n");
      out.write("        \t\t <br/><br/> ⓒCopyright 2018 All rights reserved.\r\n");
      out.write("        \t</div>\t\t\r\n");
      out.write("    \t</footer>\r\n");
      out.write(" </div> <!-- <div id=\"container\"> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
