/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-18 11:34:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import semi.kh.product.model.vo.*;
import java.util.*;
import java.net.URLEncoder;
import java.text.DecimalFormat;
import semi.kh.product.model.vo.*;
import java.util.*;
import semi.kh.board.model.vo.*;
import semi.kh.member.model.vo.*;
import semi.kh.product.model.service.*;
import java.net.URLEncoder;
import java.util.*;

public final class productView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1547621309758L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1547621309705L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("semi.kh.member.model.vo");
    _jspx_imports_packages.add("semi.kh.board.model.vo");
    _jspx_imports_packages.add("semi.kh.product.model.service");
    _jspx_imports_packages.add("semi.kh.product.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.text.DecimalFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
boolean saveId = false;
String memberId = "";

Cookie[] cookies = request.getCookies();

for(Cookie c : cookies){
	String key = c.getName();
	String value = c.getValue();
	if("saveId".equals(key)){
		saveId = true;
		memberId = value;
	}
}




      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>SHOPINGMALL</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/Chart.bundle.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/PPRbgb.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("div.login-container input[type=button]{\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("\theight:25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr#lasttr input[type=button]{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\twidth:115px;\r\n");
      out.write("\theight:25px;\r\n");
      out.write("\tright:58px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("div.login-container input[type=checkbox]{\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\ttop:50px;\r\n");
      out.write("\tright: 45px;\r\n");
      out.write("}\r\n");
      out.write("div.login-container label{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\tcolor:rgb(51,122,194);\r\n");
      out.write("\ttop:50px;\r\n");
      out.write("\tright: 6px;\r\n");
      out.write("}\r\n");
      out.write("div.login-container input[type=submit]{\r\n");
      out.write("\t\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\twidth: 60px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\ttop:13px;\r\n");
      out.write("\tright: 3px;\r\n");
      out.write(" \tpadding: 5px 5px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr#log input[type=button]{\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("}\r\n");
      out.write("#btn-logout{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\tright:60px;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#time{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("\ttop:10px;\r\n");
      out.write("}\r\n");
      out.write("#timer-button{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tfont-size:5;\r\n");
      out.write("\twidth:45px;\r\n");
      out.write("\tleft:34px;\r\n");
      out.write("\ttop:3px;\r\n");
      out.write("}\r\n");
      out.write("#title{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\tmargin-top:-10px;\r\n");
      out.write("\tmargin-left:20px;\r\n");
      out.write(" \tfont-size:50px;\r\n");
      out.write(" \tcolor:rgb(110,102,92);\r\n");
      out.write("}\r\n");
      out.write("#title:hover{\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function loginValidate() {\r\n");
      out.write("\tif($(\"#memberId\").val().trim().length ==0){\r\n");
      out.write("\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t$(\"#memberId\").focus();\r\n");
      out.write("\t\treturn false;//폼 전송 방지\r\n");
      out.write("\t}\r\n");
      out.write("\tif($(\"#password\").val().trim().length==0){\r\n");
      out.write("\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t$(\"#password\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t//form에서 유효성 검사할때는 onsubmit, 로그인버튼 부분에서 유효성검사할때는 onclick\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("function findPassword(){\r\n");
      out.write("\tvar url = \"");
      out.print(request.getContextPath());
      out.write("/member/findPassword\";\r\n");
      out.write("\tvar title =\"findPassword\";\r\n");
      out.write("\tvar status = \"left=500px,top=200px,width=400px,height=210px\";\r\n");
      out.write("\topen(url,title,status);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
if(memberLoggedIn!=null && !("admin".equals(memberLoggedIn.getMemberId()))) {
      out.write("\r\n");
      out.write("\r\n");
      out.write("var iM = 30;\r\n");
      out.write("var iS = iM * 60;\r\n");
      out.write("var timerchecker = null;\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\tfncClearTime();\r\n");
      out.write("\tinitTimer();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("Lpad = function(str,len){\r\n");
      out.write("\tstr = str + \"\";\r\n");
      out.write("\twhile(str.length < len){\r\n");
      out.write("\t\tstr = \"0\"+str;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn str;\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("initTimer = function(){\r\n");
      out.write("\trM = parseInt(iS/60);\r\n");
      out.write("\trS = iS % 60;\r\n");
      out.write("\tif(iS>0){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#time\").text(Lpad(rM,2)+\"M \"+Lpad(rS,2)+\"S\");\r\n");
      out.write("\t\tiS--;\r\n");
      out.write("\t\ttimerchecker = setTimeout(\"initTimer()\",1000);\r\n");
      out.write("\t}else {\r\n");
      out.write("\t\tclearTimeout(timerchecker);\r\n");
      out.write("\t\tlogout();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fncClearTime(){\r\n");
      out.write("\tiM = 30;\r\n");
      out.write("\tiS = iM*60;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function logout(){\r\n");
      out.write("\tlocation.href='");
      out.print(request.getContextPath());
      out.write("/member/logout';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("function goToPrdList(obj){\r\n");
      out.write("\t\r\n");
      out.write("\t  var pCategory = $(obj).attr(\"name\");\r\n");
      out.write("\t  console.log($(obj).parent().eq(0));\t /*모바일, 스마트폰,태블릿, 웨어러블 */\r\n");
      out.write("\t ");
      out.write(" \r\n");
      out.write("\t  location.href = \r\n");
      out.write("\t \t  \"");
      out.print(request.getContextPath());
      out.write("/product/productList?pCategory=\"+pCategory;\r\n");
      out.write("\t \r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t<div id=\"title\" onclick=\"location.href ='");
      out.print(request.getContextPath());
      out.write("/'\">\r\n");
      out.write("\t\t\t<img src='");
      out.print(request.getContextPath());
      out.write("/images/LOGO.png' style=\"width: 80px;\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<!-- 로그인 폼 -->\r\n");
      out.write("\t\t\t<!-- 로그인 시작 -->\r\n");
      out.write("\t\t\t<div class=\"login-container\">\r\n");
      out.write("\t\t\t");
if(memberLoggedIn == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/member/login\" method=\"post\" id=\"LoginFrm\" onsubmit=\"return loginValidate();\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"memberId\" id=\"memberId\" placeholder=\"아이디\" value=\"");
      out.print(memberId);
      out.write("\" style=\"width:170px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" id=\"password\" placeholder=\"비밀번호\" style=\"width:170px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"submit\" class=\"btn btn-primary\" value=\"로그인\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-link\" value=\"비밀번호찾기\"  onclick=\"findPassword();\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-link\" value=\"회원가입\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll'\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"saveId\" id=\"saveId\" ");
      out.print(saveId?"checked":"" );
      out.write("/> \r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"saveId\">ID저장</label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr id=\"lasttr\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-link\" value=\"비회원 주문조회\" onclick=\"location.href = '");
      out.print(request.getContextPath());
      out.write("/product/noneOrderView'\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t");
 }
				else {
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<table id=\"logged-in\">\r\n");
      out.write("\t\t\t\t\t\t<tr id=\"welcome\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(memberLoggedIn.getMemberId() );
      out.write("님, 안녕하세요! Welcome:)</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr id=\"log\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-link\" value=\"내정보보기\" onclick='location.href = \"");
      out.print(request.getContextPath());
      out.write("/member/memberView?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\";' />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" id=\"btn-logout\" value=\"로그아웃\" class=\"btn btn-link\" onclick =\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout';\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td> \r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t");
 if(!("admin".equals(memberLoggedIn.getMemberId()))) {
      out.write("\r\n");
      out.write("\t\t\t\t\t<table id=\"timer\">\r\n");
      out.write("\t\t\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t\t<td id=\"time\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"timer-button\"><input type=\"button\" class=\"btn btn-link\" value=\"연장\" onclick=\"fncClearTime();\"/></td>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 로그인 폼 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 메인메뉴 시작 -->\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<ul class=\"main-nav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a onclick=\"goToPrdList(this);\" name=\"모바일\">모바일</a>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub-nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a onclick=\"goToPrdList(this);\" name=\"스마트폰\">스마트폰</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a onclick=\"goToPrdList(this);\" name=\"태블릿\">태블릿</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a onclick=\"goToPrdList(this);\" name=\"웨어러블\">웨어러블</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\t\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a onclick=\"goToPrdList(this);\" name=\"PC\">PC</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub-nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a onclick=\"goToPrdList(this);\" name=\"노트북\">노트북</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a onclick=\"goToPrdList(this);\" name=\"모니터\">모니터</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a onclick=\"goToPrdList(this);\" name=\"데스크탑\">데스크탑</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/board/boardList\">고객센터</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/product/productCart\">장바구니</a></li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t ");
      out.write("\r\n");
      out.write("               ");
if(memberLoggedIn != null && ("admin").equals(memberLoggedIn.getMemberId())){ 
      out.write("\r\n");
      out.write("               <li>\r\n");
      out.write("                  <a href=\"#\">관리자</a>\r\n");
      out.write("                  <ul class=\"sub-nav\">\r\n");
      out.write("                     <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">회원관리</a></li>                              \r\n");
      out.write("                     <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberManagement\">통계</a></li>\r\n");
      out.write("                     <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/Management\">스케줄러</a></li>\r\n");
      out.write("                     <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/orderView\">주문내역</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </li>\r\n");
      out.write("               ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!-- 메인메뉴 끝 -->\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div id=\"wrapper\" style=\"position:relative\">\r\n");
      out.write("\t\t<div id=\"todayList\" style=\"position:absolute; width:130px; min-height:100px; left:970px;\">\r\n");
      out.write("\t\t<h6 id=\"todayList_h6\"> 최근 본 상품</h6>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar arr = new Array();\r\n");
      out.write("\t\t");

		request.setCharacterEncoding("UTF-8");
		Cookie[] pcookies = request.getCookies();
		
		
		for(Cookie pc : pcookies){
			String key = pc.getName();
			String value = pc.getValue();
			
			if(key.contains("pcc")){
		
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tvar todayList = new Object();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.log(\"length\"+arr.length);\r\n");
      out.write("\t\t\tif(arr.length >=5){\r\n");
      out.write("\t\t\t\tarr.shift();\r\n");
      out.write("\t\t\t\ttodayList.toID=\"");
      out.print( key.substring(3) );
      out.write("\";\r\n");
      out.write("\t\t\t\ttodayList.toNAME=\"");
      out.print( value );
      out.write("\";\r\n");
      out.write("\t\t\t\tarr.push(todayList);\r\n");
      out.write("\t\t\t}else {\r\n");
      out.write("\t\t\t\ttodayList.toID=\"");
      out.print( key.substring(3) );
      out.write("\";\r\n");
      out.write("\t\t\t\ttodayList.toNAME=\"");
      out.print( value );
      out.write("\";\r\n");
      out.write("\t\t\t\tarr.push(todayList);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
 
				
			}
		}
		
		
      out.write("\r\n");
      out.write("\t\t\tvar addr = \"");
      out.print(request.getContextPath() );
      out.write("/product/productView?pId=\";\r\n");
      out.write("\t\t\tvar html1 = \"<a href='\";\r\n");
      out.write("\t\t\tvar html2 = \"' >\"\r\n");
      out.write("\t\t\tvar html3 = \"</a>\";\r\n");
      out.write("\t\t\tvar src1 = \"<img class='listimg' src='\";\r\n");
      out.write("\t\t\tvar src2 = \"");
      out.print(request.getContextPath() );
      out.write("/images/product/\";\r\n");
      out.write("\t\t\tvar src3 = \"_thumb1.png' \"+\"onerror= javascript:this.src='");
      out.print(request.getContextPath() );
      out.write("/images/error_thumb.jpg'\"+\" />\";\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\tfor(var i in arr){\r\n");
      out.write("\t\t\t\t$(\"#todayList\").append( \"<div class='todayList_list'>\"+html1+addr+arr[i].toID+html2+src1+src2+arr[i].toNAME+src3+\" <br />\" +arr[i].toNAME+ \"<br /></h6>\"+html3+\"</div>\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<section id=\"content\" style=\"background:none;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/PPRbgb.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/productView.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.5.0/css/all.css\" integrity=\"sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU\" crossorigin=\"anonymous\">\r\n");

	request.setCharacterEncoding("UTF-8");
	Product p = (Product)request.getAttribute("Product");
	
	/*최근 본 상품 쿠키*/
	Cookie[] pC = request.getCookies();
	for(int j =0;j<pC.length;j++){	    
	     if((pC[j].getName()).contains(p.getpId())){ // 중복일때
	        
	                Cookie pcc = new Cookie("pcc"+p.getpId(),null); //기존것 제거
	                pcc.setMaxAge(0);
	                pcc.setPath("/hdj");
	                response.addCookie(pcc);
	                
	                pcc = new Cookie("pcc"+p.getpId(),p.getpName()); //새로 추가
	                pcc.setMaxAge(2*60);//세션유지 2분
	                pcc.setPath("/hdj");
	                response.addCookie(pcc);
	           	    
	        }else{ //중복이 아닐때	   
	                Cookie pcc = new Cookie("pcc"+p.getpId(),p.getpName()); //추가
	                pcc.setMaxAge(2*60);//세션유지 2분
	                pcc.setPath("/hdj");
	                response.addCookie(pcc);
	      }	        
	}

	List<BoardReview> reviewList = (List<BoardReview>)request.getAttribute("reviewList");	
	int reviewtotalCnt = (int)request.getAttribute("reviewtotalCnt");
   
	List<Board> qnaList = (List<Board>)request.getAttribute("qnaList");
	List<BoardComment> qnaCommentList = (List<BoardComment>)request.getAttribute("qnaCommentList");
	
	String QnApageBar = (String)request.getAttribute("pageBar");
	//int cPage = (int)request.getAttribute("cPage");
	String category = request.getParameter("category");
	
	String loggedInId = memberLoggedIn==null?"":memberLoggedIn.getMemberId();
	

      out.write(" \r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\t\r\n");
      out.write("\t\r\n");
      out.write("\tif('qna'=== '");
      out.print(category);
      out.write("'){ //qna 리스트\r\n");
      out.write("\t\t$(\".list_detail_category button\").parent().eq(2).addClass('on');\r\n");
      out.write("\t\t$(\".box-detail\").eq(2).addClass('show');\r\n");
      out.write("\t\t\r\n");
      out.write("\t}else{ //상세보기 이미지\r\n");
      out.write("\t\t$(\".list_detail_category button\").parent().eq(0).addClass('on');\r\n");
      out.write("\t\t$(\".box-detail\").eq(0).addClass('show');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".list_detail_category button\").on(\"click\",function(){//버튼 다 걸림\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar parent = $(this).parent();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(this).parent().addClass('on');\r\n");
      out.write("\t\t$(\".list_detail_category li\").not(parent).removeClass('on');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar index = $('.on').index();\r\n");
      out.write("\t\tvar element = $('div.wrap-box-datail').children().eq(index);\r\n");
      out.write("\t\telement.addClass('show');\r\n");
      out.write("\t\t\r\n");
      out.write("\t \t$('.wrap-box-datail div').not(element).removeClass('show');\r\n");
      out.write("\r\n");
      out.write("\t}); //정보 탭 바꾸기\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t$(\".btn_comment\").click(function(){ //답변버튼\r\n");
      out.write("\t\tvar $element = $(this).closest('tr').next('tr').next('tr'); \r\n");
      out.write("\t\t$(\"tr.QnAComment-editor\").css(\"display\",\"none\"); //나머지는 숨기기\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$element.css(\"display\",\"\"); //해당하는거만 보여주기\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"img.prod-image-list-thumb\").on(\"click\",function(){\r\n");
      out.write("\t\t$('img.prod-image-detail').attr('src',$(this).attr('src'));\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("var v_flag = false;\r\n");
      out.write("\r\n");
      out.write("function p_fun(flag,no){\t\r\n");
      out.write("\tv_flag = flag; \r\n");
      out.write("\t\r\n");
      out.write("\tif(flag){\t\t\r\n");
      out.write("\t\tif(v_flag){\r\n");
      out.write("\t\t\t$(\"#\"+no).closest('tr').css(\"background\",\"#f9f9f9\"); \r\n");
      out.write("\t\t\t$(\"#\"+no).closest('tr').next('.QnAContent').css(\"display\",\"\").css(\"background\",\"#f9f9f9\"); // 다음행 (질문내용)\r\n");
      out.write("\t\t\t$(\"#\"+no).closest('tr').next('tr').next('.QnACommentContent').css(\"display\",\"\"); //다다음행(답변)\t  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkId(flag,writer,no){\r\n");
      out.write("\r\n");
      out.write("\t$(\"tr.QnATitle\").css(\"background\",\"none\");\r\n");
      out.write("\t$(\"tr.QnAContent\").css(\"display\",\"none\");\r\n");
      out.write("\t$(\"tr.QnACommentContent\").css(\"display\",\"none\");\r\n");
      out.write("\r\n");
      out.write("  if(flag === 'N'){  \r\n");
      out.write("\t\t$(\"#\"+no).closest('tr').css(\"background\",\"#f9f9f9\"); \r\n");
      out.write("\t\t$(\"#\"+no).closest('tr').next('.QnAContent').css(\"display\",\"\").css(\"background\",\"#f9f9f9\"); // 다음행 (질문내용)\r\n");
      out.write("\t\t$(\"#\"+no).closest('tr').next('tr').next('.QnACommentContent').css(\"display\",\"\"); //다다음행(답변)\t  \r\n");
      out.write("  }else{ //비밀글\r\n");
      out.write("\t  \r\n");
      out.write("\t  //비회원이면\r\n");
      out.write("\t  if('");
      out.print(memberLoggedIn );
      out.write("'=== 'null'){\r\n");
      out.write("\t\t  //비밀번호 체크창 띄우기\r\n");
      out.write("\t \t\tvar url = \"");
      out.print(request.getContextPath() );
      out.write("/board/ChkQnaBoardPwd?boardNo=\"+no;\r\n");
      out.write("\t\t\tvar title = \"checkQnaPwd\";\r\n");
      out.write("\t\t\tvar status = \"left=500px, top=200px, width=400px, height=210px\"\r\n");
      out.write("\t\t\topen(url,title,status); //자식창 열기  \r\n");
      out.write("\t  }\r\n");
      out.write(" \t //로그인값이 notnull이면 (로그인을 했다면)\r\n");
      out.write("\t  else{\r\n");
      out.write("\t\t  //회원이거나 admin 이면\t  \r\n");
      out.write("\t\t  if(\"admin\" === '");
      out.print(loggedInId);
      out.write("'|| writer === '");
      out.print(loggedInId);
      out.write("'){\r\n");
      out.write("\t\t\t$(\"#\"+no).closest('tr').css(\"background\",\"#f9f9f9\"); \r\n");
      out.write("\t\t\t$(\"#\"+no).closest('tr').next('.QnAContent').css(\"display\",\"\").css(\"background\",\"#f9f9f9\"); // 다음행 (질문내용)\r\n");
      out.write("\t\t\t$(\"#\"+no).closest('tr').next('tr').next('.QnACommentContent').css(\"display\",\"\"); //다다음행(답변)\t  \r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  }  \r\n");
      out.write("  }\r\n");
      out.write("} // function checkId\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function number_check(e){\r\n");
      out.write("\t var code = e.which?e.which:event.keyCode;\r\n");
      out.write("\t    if(code < 48 || code > 57){\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function check(){\r\n");
      out.write("\t\r\n");
      out.write("\tif($(\"input[name='lockflag']\").is(':checked') ){\r\n");
      out.write("\t $(\"input[name='lockflag']\").val(\"Y\");\r\n");
      out.write("\t $(\"input[name='password']\").prop(\"required\", true);\r\n");
      out.write("\t $(\"input[name='password']\").prop(\"readonly\", false);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$(\"input[name='lockflag']\").val(\"N\");\r\n");
      out.write("\t\t$(\"input[name='password']\").val(\"\");\r\n");
      out.write("\t\t$(\"input[name='password']\").prop(\"required\", false);\r\n");
      out.write("\t\t$(\"input[name='password']\").prop(\"readonly\", true);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function like(bno , recommend , writer , memberid){\r\n");
      out.write("    \r\n");
      out.write("    if(writer === memberid){\r\n");
      out.write("        alert(\"본인 후기에 추천할 수 없습니다.\");\r\n");
      out.write("    }else if(writer != memberid){\r\n");
      out.write("    console.log(bno);\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: \"");
      out.print(request.getContextPath());
      out.write("/review/recommend.do\",\r\n");
      out.write("        type: \"get\",\r\n");
      out.write("        data: \"bno=\"+bno+\"&recommend=\"+recommend+\"&memberid=\"+memberid,\r\n");
      out.write("        success : function(data){\r\n");
      out.write("            console.log(\"index.jsp@data\"+data); //자바스크립트 형태\r\n");
      out.write("             $(\"#\"+bno).html(data);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("function logcheck(){\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("            alert(\"비회원은 추천할 수 없습니다.\");\r\n");
      out.write("    \r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<section id=\"product-container\">\t\r\n");
      out.write("<!-- 상품 이미지와 주문/장바구니 ------------>\t\r\n");
      out.write("\t<div class=\"prod-atf\">\r\n");
      out.write("\t\t<div class=\"prod-image\">\r\n");
      out.write("\t\t\t<div class=\"prod-image-list\">\r\n");
      out.write("\t\t\t\t<img class= \"prod-image-list-thumb\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/product/");
      out.print(p.getpName() );
      out.write("_thumb1.png\"\r\n");
      out.write("\t\t\t\t\t onError=\"javascript:this.src='");
      out.print(request.getContextPath());
      out.write("/images/error_thumb.jpg'\"/>\r\n");
      out.write("\t\t\t\t<img class= \"prod-image-list-thumb\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/product/");
      out.print(p.getpName() );
      out.write("_thumb2.png\"\r\n");
      out.write("\t\t\t\t\t onError=\"javascript:this.src='");
      out.print(request.getContextPath());
      out.write("/images/error_thumb.jpg'\"/>\r\n");
      out.write("\t\t\t\t<img class= \"prod-image-list-thumb\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/product/");
      out.print(p.getpName() );
      out.write("_thumb3.png\"\r\n");
      out.write("\t\t\t\t\t onError=\"javascript:this.src='");
      out.print(request.getContextPath());
      out.write("/images/error_thumb.jpg'\"/>\r\n");
      out.write("\t\t\t\t<img class= \"prod-image-list-thumb\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/product/");
      out.print(p.getpName() );
      out.write("_thumb4.png\"\r\n");
      out.write("\t\t\t\t\t onError=\"javascript:this.src='");
      out.print(request.getContextPath());
      out.write("/images/error_thumb.jpg'\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<img class=\"prod-image-detail\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/product/");
      out.print(p.getpName() );
      out.write("_thumb1.png\" \r\n");
      out.write("\t\t\t\t onError=\"javascript:this.src='");
      out.print(request.getContextPath());
      out.write("/images/error_thumb.jpg'\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"prod-buy-info\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"prod-buy-header\">\r\n");
      out.write("\t\t\t\t<h2 class=\"prod-buy-pName\">");
      out.print(p.getpName() );
      out.write("</h2>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"prod-buy-score\">\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(reviewtotalCnt );
      out.write(" 개 상품평</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div> <!--prod-buy-header -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"prod-price-container\">\r\n");
      out.write("\t\t\t\t<!-- 재고량 0 이면 품절 표시! -->\r\n");
      out.write("\t\t\t\t");
 if(p.getpStock()==0){ 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<span class=\"soldout\">품절</span>\t\t\r\n");
      out.write("\t\t\t\t");
}else{
					String price = new DecimalFormat().format(p.getpPrice());	
				
      out.write("\t\r\n");
      out.write("\t\t\t\t<span class=\"pPrice\">\r\n");
      out.write("\t\t\t\t\t<strong>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(price);
      out.write("<span class=\"price-unit\">원</span>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</div> <!-- prod-price-container -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"prod-pcompany-container\">\r\n");
      out.write("\t\t\t\t<span class=\"pId\">모델 : ");
      out.print(p.getpId() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span class=\"pCompany\" style=\"color : #346aff\">");
      out.print(p.getpCompany() );
      out.write("</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 수량 표시 -->\r\n");
      out.write("\t\t\t<div class=\"quantity\">\r\n");
      out.write("  \t\t\t\t<input type=\"number\" id=\"quantity\" min=\"1\" max=\"9\" step=\"1\" value=\"1\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t$(\"#quantity\").on(\"change\", function(){\r\n");
      out.write("\t\t\t\t$(\"[name='amount']\").val($(this).val());\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction orderValidate(){\r\n");
      out.write("\t\t\t\tvar orderamount = $(\"[name=amount]\").val();\r\n");
      out.write("\t\t\t\tvar pName = $(\"[name=pName]\").val();\r\n");
      out.write("\t\t\t\tvar price = $(\"[name=pPrice]\").val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(!confirm(pName + \" \" + orderamount + \"개를 주문하시겠습니까? (총 금액 : \"+ orderamount*price +\")\")){\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"prod-buy-footer\">\t\t\t   \t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"prod-onetime-order\">\t\t\t\r\n");
      out.write("         \t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/product/productAddItem\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"pId\" value=\"");
      out.print(p.getpId() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"pName\" value=\"");
      out.print(p.getpName() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"pPrice\" value=\"");
      out.print(p.getpPrice());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"amount\" value=\"1\"/>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"prod-cart-btn\">장바구니담기</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/product/productDirectBuy\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"pId\" value=\"");
      out.print(p.getpId() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"pName\" value=\"");
      out.print(p.getpName() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"pPrice\" value=\"");
      out.print(p.getpPrice());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"amount\" value=\"1\"/>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"prod-buy-btn\" onclick=\"return orderValidate();\">바로구매</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("\t\t\t</div> <!-- prod-buy-footer -->\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div> <!--prod-buy-info -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<!-- 상품관련 카테고리 버튼 ---------------->\r\n");
      out.write("\t<div class=\"wrap-detail-category\" style = \"padding-bottom : 0;\">\r\n");
      out.write("\t\t<div class=\"inner\" style = \"padding : 0;\">\r\n");
      out.write("\t\t\t<ul class=\"list_detail_category\">\r\n");
      out.write("\t\t\t\t<li><button type=\"button\" class=\"tab_detail_info\">상세정보</button></li>\r\n");
      out.write("\t\t\t\t<li><button type=\"button\" class=\"tab_detail_ps\">구매후기</button></li>\r\n");
      out.write("\t\t\t\t<li><button type=\"button\" class=\"tab_detail_qna\">Q&A</button></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"wrap-box-datail\">\r\n");
      out.write("\t\r\n");
      out.write("<!-- 상세정보 --------------------------->\r\n");
      out.write("\t<div class=\"box-detail\">\r\n");
      out.write("\t\t<div class=\"inner_border\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/product/");
      out.print(p.getpName() );
      out.write("_description.png\" \r\n");
      out.write("\t\t\t\t onError=\"javascript:this.src='");
      out.print(request.getContextPath());
      out.write("/images/error_thumb.jpg'\"\r\n");
      out.write("\t\t\t\t style=\"padding-top : 50px;\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<!-- REVIEW ---------------------------->\r\n");
      out.write("\t<div class=\"box-detail\"> \r\n");
      out.write("\t\t<div class=\"inner_border\">\r\n");
      out.write("\t\t\t<ul class=\"review-container\">\r\n");
      out.write("\t\t\t <table style=\" width:800px; text-align:center;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 if(reviewList == null || reviewList.isEmpty()) { 
      out.write("\r\n");
      out.write("\t\t\t\t <tr style=\"border-bottom:0.2px solid lightgray;\"><td colspan=\"4\" align=\"center\" height=\"100px\">리뷰가 없습니다.</td></tr>  \r\n");
      out.write("         \t");
} else { 
           		for(BoardReview br : reviewList){ 			 
			  
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t<tr style=\"border-bottom:0.2px solid lightgray;\">\r\n");
      out.write("\t\t\t\t  \t</td>\r\n");
      out.write("\t\t\t\t    \t");
if(br.getRfile()!= null){ 
      out.write("\r\n");
      out.write("\t\t\t\t    \t<td>\r\n");
      out.write("\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t\t<img src='");
      out.print(request.getContextPath());
      out.write("/upload/board/");
      out.print(br.getRfile());
      out.write("' style=\"height:100px; width:150px;\"> </td>\r\n");
      out.write("\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td>&nbsp;&nbsp;&nbsp;");
      out.print(br.getPid() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t  \t \r\n");
      out.write("\t\t\t\t  \t<td style=\"width:228px;text-align:left; \"><span class=\"post\" >");
      out.print(br.getContent() );
      out.write("</span></td>\r\n");
      out.write("\t\t\t\t  \t<td style=\"width:200px; \">\r\n");
      out.write("\t\t\t\t  \t<br>\r\n");
      out.write("\t\t\t\t    <span class=\"review-score\" value =");
      out.print(br.getRate() );
      out.write(">\r\n");
      out.write("\t\t\t\t    \t<div style=\" width: 115px; padding: 0; overflow: hidden;\">\r\n");
      out.write("\t\t\t\t    \t");
if(br.getRate() == 5 ){ 
      out.write("\r\n");
      out.write("\t\t\t\t   \t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/graystar.PNG\" style=\"width:100px; margin-right: 13px; \"/>\r\n");
      out.write("\t\t\t\t    \t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/star.png\" style=\"width:100px; height: 23px;margin-top: -31px;margin-right: 13px; \"/>\r\n");
      out.write("\t\t\t\t    \t");
}else if(br.getRate() == 4 ){
      out.write("\r\n");
      out.write("\t\t\t\t    \t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/graystar.PNG\" style=\"width:100px; margin-right: 13px; \"/>\r\n");
      out.write("\t\t\t\t    \t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/star.png\" style=\"width:100px; height: 23px;margin-top: -31px;margin-right: 13px; margin-left: -41px;\"/>\r\n");
      out.write("\t\t\t\t    \t");
}else if(br.getRate() == 3 ){
      out.write("\r\n");
      out.write("\t\t\t\t    \t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/graystar.PNG\" style=\"width:100px; margin-right: 13px; \"/>\r\n");
      out.write("\t\t\t\t    \t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/star.png\" style=\"width:100px; height: 23px;margin-top: -31px;margin-right: 13px; margin-left: -82px;\"/>\r\n");
      out.write("\t\t\t\t    \t");
}else if(br.getRate() == 2 ){
      out.write("\r\n");
      out.write("\t\t\t\t    \t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/graystar.PNG\" style=\"width:100px; margin-right: 13px; \"/>\r\n");
      out.write("\t\t\t\t    \t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/star.png\" style=\"width:100px; height: 23px;margin-top: -31px;margin-right: 13px; margin-left: -122px;\"/>\r\n");
      out.write("\t\t\t\t    \t");
}else if(br.getRate() == 1 ){
      out.write("\r\n");
      out.write("\t\t\t\t    \t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/graystar.PNG\" style=\"width:100px; margin-right: 13px; \"/>\r\n");
      out.write("\t\t\t\t    \t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/star.png\" style=\"width:100px; height: 23px;margin-top: -31px;margin-right: 13px; margin-left: -161px;\"/>\r\n");
      out.write("\t\t\t\t    \t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t    </span>    \r\n");
      out.write("\t\t\t\t    <p style=\"margin-left: -16px;\">\r\n");
      out.write("\t\t\t\t  \t");
if(br.getWriter().length() <= 19){ 
      out.write("\r\n");
      out.write("\t\t\t\t  \t");
      out.print(br.getWriter());
      out.write("　　　　　\r\n");
      out.write("\t\t\t\t  \t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t  \t비회원　　　　　\r\n");
      out.write("\t\t\t\t  \t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t  \t<p>\r\n");
      out.write("\t\t\t\t  \t\r\n");
      out.write("\t\t\t\t  \t");
if(memberLoggedIn != null ){ 
      out.write("\r\n");
      out.write("      \t\t\t\t<i class=\"far fa-thumbs-up\" id=\"like\" onclick=\"like('");
      out.print(br.getbNo() );
      out.write("' ,'");
      out.print(br.getRecommend() );
      out.write("' ,'");
      out.print(br.getWriter());
      out.write("' , '");
      out.print(memberLoggedIn.getMemberId() );
      out.write("');\" style=\"margin-left: -120px; cursor:pointer;\"></i>\r\n");
      out.write("      \t\t\t\t<span id=\"");
      out.print(br.getbNo());
      out.write("\">&nbsp;&nbsp;");
      out.print(br.getRecommend() );
      out.write("</span>\r\n");
      out.write("      \t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("      \t\t\t\t\t<i class=\"far fa-thumbs-up\" id=\"like\" onclick=\"logcheck();\" style=\"margin-left: -120px; cursor:pointer;\"></i>\r\n");
      out.write("      \t\t\t\t<span >&nbsp;&nbsp;");
      out.print(br.getRecommend() );
      out.write("</span>\r\n");
      out.write("      \t\t\t\t");
} 
      out.write("\r\n");
      out.write("      \t\t\t\t<div class=\"date\" style=\"margin-left: -95px; padding-top: 0px; padding-bottom: 20px; \">");
      out.print(br.getBdate() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("      \t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
 }
				}	
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("    \t\t</ul>\r\n");
      out.write("    \t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<!-- QNA ------------------------------->\r\n");
      out.write("\t<div class=\"box-detail\">\r\n");
      out.write("\t\t<div class=\"inner_border\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- QnA 입력창-->\r\n");
      out.write("\t\t\t<div class=\"QnA-editor\">\r\n");
      out.write("\t\t\t\t<h4 class=\"tit prdt_iqry\">상품 문의</h4>\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/board/qnaBoardFormEnd\" method=\"post\" name=\"boardQnAFrm\" >\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style=\"display : table;\">\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"pId\" value=\"");
      out.print(p.getpId());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\"  name=\"writer\" \r\n");
      out.write("\t\t\t\t\t\t\t  value=");
      out.print(memberLoggedIn!=null?memberLoggedIn.getMemberId():"비회원" );
      out.write(" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"category\" value=\"상품문의\"/>          \t\t   \r\n");
      out.write("\t\t\t\t\t   \t제목\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t \t<input type=\"text\" name=\"title\" class=\"form-control\" required>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"lockflag\" value=\"N\" onclick=\"check();\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
if(memberLoggedIn == null){ 
      out.write("<!-- 비회원일 경우 보이게 하기 -->\r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"password\" size='5' maxlength=\"4\" name=\"password\" placeholder=\"비밀번호\" \r\n");
      out.write("\t\t\t\t\t\t\t \t\tonkeypress=\"return number_check(event)\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"display:inline-block; width: 94px; text-align: left;\">비밀글</span>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
 }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\" cols=\"60\" rows=\"3\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\">질문하기</button>\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t</div><!-- QnAComment-editor -->\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<!-- QnA 리스트  -->\t\t\r\n");
      out.write("    \t<table id=\"tbl-qna\" style =\"border-collapse: collapse;\"> \r\n");
      out.write("      \t\t<tr><th>답변여부</th><th>카테고리</th><th>제목</th><th>작성자</th><th>등록일</th><th></th></tr>\r\n");
      out.write("\r\n");
      out.write("\t\t");
 if(qnaList == null || qnaList.isEmpty()) { 
      out.write("\r\n");
      out.write("            <tr><td colspan=\"6\" align=\"center\" height=\"100px\">검색결과가 없습니다.</td></tr>\r\n");
      out.write("\t    ");
 }else { 
            
	    	for(Board b : qnaList) { 
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr class= \"QnATitle\" style=\"background: none;\">\r\n");
      out.write("\t\t\t \t<!-- 답변여부(미답변/답변) -->\r\n");
      out.write("\t\t\t ");
 if(b.getBoardCommentCnt() <= 0){ 
      out.write(" \r\n");
      out.write("\t\t\t \t<td>미답변</td>\t\t\t\r\n");
      out.write("\t\t\t ");
} else {
      out.write(" \r\n");
      out.write("\t\t\t \t<td>답변완료</td>  \r\n");
      out.write("\t\t\t ");
} 
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t \t<!-- 카테고리(상품문의) -->\t\r\n");
      out.write("\t\t\t\t<td>");
      out.print(b.getBcategory() );
      out.write("</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<!-- QnA글 제목(비밀글 여부 판단함수) ---------------------------------------->\r\n");
      out.write("\t\t\t\t<td style=\"cursor:pointer;\" onclick=\"checkId('");
      out.print(b.getbLockFlag());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(b.getbWriter());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(b.getBoardNo());
      out.write("');\" id=\"");
      out.print(b.getBoardNo());
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(b.getBoardTitle());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
if("Y".equals(b.getbLockFlag())) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t&nbsp;<i class=\"fas fa-lock\" id=\"lockqna\"></i>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</td>\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<td>");
      out.print(b.getbWriter() );
      out.write("</td><!-- 작성자 -->\r\n");
      out.write("\t\t\t\t<td>");
      out.print(b.getBoardDate() );
      out.write("</td><!-- 작성일 -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 답변이 안되어있고, admin이 로그인 했을 때만 답변 버튼 보여주기  -->\r\n");
      out.write("\t\t\t\t");
 if(b.getBoardCommentCnt()<= 0 && memberLoggedIn!= null && "admin".equals(memberLoggedIn.getMemberId())){ 
      out.write("\r\n");
      out.write("\t\t\t\t<td style=\"width: 70px;\"> \r\n");
      out.write("\t\t\t\t\t<button type=\"button\" name=\"btn_comment\" class=\"btn_comment\">답변</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t<td> </td>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- 제목을 클릭하면 내용이 보이도록 -->\r\n");
      out.write("\t\t\t<tr class=\"QnAContent\" style=\"display : none; height: 77px;\">\r\n");
      out.write("\t\t\t  <td colspan = \"6\">");
      out.print(b.getbConetent() );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- QnA 코멘트 추가  -->\r\n");
      out.write("\t\t\t\t");
for(BoardComment bc : qnaCommentList) {
					if(b.getBoardNo() == bc.getcRef()){
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr class=\"QnACommentContent\" style=\"display : none;\">\r\n");
      out.write("\t\t\t\t\t<td><div>└</div></td>\r\n");
      out.write("\t\t\t\t\t<td colspan = \"5\" style=\"text-align : left;\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(bc.getcContent() );
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t<br />| ");
      out.print(bc.getcDate() );
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t");
 } 
				} 
      out.write(" <!-- end of for(qnaCommentList) -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 if(b.getBoardCommentCnt()<= 0){ 
      out.write("\r\n");
      out.write("\t\t\t<tr class=\"QnAComment-editor\" style='display: none;'>\r\n");
      out.write("\t\t\t<td colspan = \"6\">\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 답변 입력창 -->\r\n");
      out.write("\t\t\t\t<div class=\"QnAComment-editor\" style=\"margin-left: 50px;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/board/boardCommentInsert\" method=\"post\" name=\"boardCommentFrm\" >\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"pId\" value=\"");
      out.print(p.getpId());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"boardRef\" value=\"");
      out.print(b.getBoardNo());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"boardCommentWriter\" value=\"[답변]\" />\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"category\" value=\"qna\"/>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display : table;\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\"form-control\" style=\"width:600px;\"name=\"boardCommentContent\" cols=\"60\" rows=\"3\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\"  class=\"btn btn-default\" >등록</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div><!-- QnAComment-editor -->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
} 
      out.write(" <!-- if(b.getBoardCommentCnt()<= 0) -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
	} //end of for(QNALIST)
         } 
      out.write(" <!--if(qnaList == null || qnaList.isEmpty())\t-->\r\n");
      out.write(" \r\n");
      out.write("     </table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t \t<div id=\"QnApageBar\">");
      out.print(QnApageBar );
      out.write("</div>\r\n");
      out.write("\t\t \t\r\n");
      out.write(" \t\t </div> <!-- inner_border -->\r\n");
      out.write(" \t   </div> <!-- box-detail -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("        \t<div>        \t \r\n");
      out.write("        \t\t  주식회사 SEMI_HDJ &nbsp;|&nbsp; CEO HDJ &nbsp;|&nbsp; BUSINESS REGISTRATION 103-88-00990 \r\n");
      out.write("        \t\t <br/><br/> ⓒCopyright 2018 All rights reserved.\r\n");
      out.write("        \t</div>\t\t\r\n");
      out.write("    \t</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </div> <!-- <div id=\"container\"> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
